services:

  go-app:
    container_name: go-app
    image: go-api-tutorial
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - go_db
      
  go_db:
    container_name: go_db
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: gabriel18
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}